//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18033
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18033.
// 
#pragma warning disable 1591

namespace bsx.DirLaguna.Advertiser.GorilaService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GorilaServiceSoap", Namespace="http://tempuri.org/")]
    public partial class GorilaService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback SignupCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback InvoiceToOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchClientConceptsOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchClientInvoicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchInvoicePdfOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchInvoiceXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchPriceByGorilaIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback OfficesFranchiseeOperationCompleted;
        
        private System.Threading.SendOrPostCallback BankAccountsFranchiseeOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterPaymentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GorilaService() {
            this.Url = global::bsx.DirLaguna.Advertiser.Properties.Settings.Default.bsx_DirLaguna_Advertiser_GorilaService_GorilaService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event SignupCustomerCompletedEventHandler SignupCustomerCompleted;
        
        /// <remarks/>
        public event InvoiceToCompletedEventHandler InvoiceToCompleted;
        
        /// <remarks/>
        public event FetchClientConceptsCompletedEventHandler FetchClientConceptsCompleted;
        
        /// <remarks/>
        public event FetchClientInvoicesCompletedEventHandler FetchClientInvoicesCompleted;
        
        /// <remarks/>
        public event FetchInvoicePdfCompletedEventHandler FetchInvoicePdfCompleted;
        
        /// <remarks/>
        public event FetchInvoiceXmlCompletedEventHandler FetchInvoiceXmlCompleted;
        
        /// <remarks/>
        public event FetchPriceByGorilaIdCompletedEventHandler FetchPriceByGorilaIdCompleted;
        
        /// <remarks/>
        public event OfficesFranchiseeCompletedEventHandler OfficesFranchiseeCompleted;
        
        /// <remarks/>
        public event BankAccountsFranchiseeCompletedEventHandler BankAccountsFranchiseeCompleted;
        
        /// <remarks/>
        public event RegisterPaymentCompletedEventHandler RegisterPaymentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SignupCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SignupCustomer(string rfc, string key, CustomerCarrier carrier, out string[] errors) {
            object[] results = this.Invoke("SignupCustomer", new object[] {
                        rfc,
                        key,
                        carrier});
            errors = ((string[])(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SignupCustomerAsync(string rfc, string key, CustomerCarrier carrier) {
            this.SignupCustomerAsync(rfc, key, carrier, null);
        }
        
        /// <remarks/>
        public void SignupCustomerAsync(string rfc, string key, CustomerCarrier carrier, object userState) {
            if ((this.SignupCustomerOperationCompleted == null)) {
                this.SignupCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignupCustomerOperationCompleted);
            }
            this.InvokeAsync("SignupCustomer", new object[] {
                        rfc,
                        key,
                        carrier}, this.SignupCustomerOperationCompleted, userState);
        }
        
        private void OnSignupCustomerOperationCompleted(object arg) {
            if ((this.SignupCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignupCustomerCompleted(this, new SignupCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InvoiceTo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InvoiceTo(string rfc, string key, CustomerCarrier customer, ConceptCarrier[] items, out string[] errors, out string folioSerie) {
            object[] results = this.Invoke("InvoiceTo", new object[] {
                        rfc,
                        key,
                        customer,
                        items});
            errors = ((string[])(results[1]));
            folioSerie = ((string)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InvoiceToAsync(string rfc, string key, CustomerCarrier customer, ConceptCarrier[] items) {
            this.InvoiceToAsync(rfc, key, customer, items, null);
        }
        
        /// <remarks/>
        public void InvoiceToAsync(string rfc, string key, CustomerCarrier customer, ConceptCarrier[] items, object userState) {
            if ((this.InvoiceToOperationCompleted == null)) {
                this.InvoiceToOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInvoiceToOperationCompleted);
            }
            this.InvokeAsync("InvoiceTo", new object[] {
                        rfc,
                        key,
                        customer,
                        items}, this.InvoiceToOperationCompleted, userState);
        }
        
        private void OnInvoiceToOperationCompleted(object arg) {
            if ((this.InvoiceToCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InvoiceToCompleted(this, new InvoiceToCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchClientConcepts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool FetchClientConcepts(string rfc, string key, out ConceptCarrier[] concepts, out string[] errors) {
            object[] results = this.Invoke("FetchClientConcepts", new object[] {
                        rfc,
                        key});
            concepts = ((ConceptCarrier[])(results[1]));
            errors = ((string[])(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void FetchClientConceptsAsync(string rfc, string key) {
            this.FetchClientConceptsAsync(rfc, key, null);
        }
        
        /// <remarks/>
        public void FetchClientConceptsAsync(string rfc, string key, object userState) {
            if ((this.FetchClientConceptsOperationCompleted == null)) {
                this.FetchClientConceptsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchClientConceptsOperationCompleted);
            }
            this.InvokeAsync("FetchClientConcepts", new object[] {
                        rfc,
                        key}, this.FetchClientConceptsOperationCompleted, userState);
        }
        
        private void OnFetchClientConceptsOperationCompleted(object arg) {
            if ((this.FetchClientConceptsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchClientConceptsCompleted(this, new FetchClientConceptsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchClientInvoices", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool FetchClientInvoices(string rfc, string key, int customerId, out InvoiceCarrier[] invoices, out string[] errors) {
            object[] results = this.Invoke("FetchClientInvoices", new object[] {
                        rfc,
                        key,
                        customerId});
            invoices = ((InvoiceCarrier[])(results[1]));
            errors = ((string[])(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void FetchClientInvoicesAsync(string rfc, string key, int customerId) {
            this.FetchClientInvoicesAsync(rfc, key, customerId, null);
        }
        
        /// <remarks/>
        public void FetchClientInvoicesAsync(string rfc, string key, int customerId, object userState) {
            if ((this.FetchClientInvoicesOperationCompleted == null)) {
                this.FetchClientInvoicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchClientInvoicesOperationCompleted);
            }
            this.InvokeAsync("FetchClientInvoices", new object[] {
                        rfc,
                        key,
                        customerId}, this.FetchClientInvoicesOperationCompleted, userState);
        }
        
        private void OnFetchClientInvoicesOperationCompleted(object arg) {
            if ((this.FetchClientInvoicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchClientInvoicesCompleted(this, new FetchClientInvoicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchInvoicePdf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FileContainerCarrier FetchInvoicePdf(string rfc, string key, int invoiceId, string ipAddress) {
            object[] results = this.Invoke("FetchInvoicePdf", new object[] {
                        rfc,
                        key,
                        invoiceId,
                        ipAddress});
            return ((FileContainerCarrier)(results[0]));
        }
        
        /// <remarks/>
        public void FetchInvoicePdfAsync(string rfc, string key, int invoiceId, string ipAddress) {
            this.FetchInvoicePdfAsync(rfc, key, invoiceId, ipAddress, null);
        }
        
        /// <remarks/>
        public void FetchInvoicePdfAsync(string rfc, string key, int invoiceId, string ipAddress, object userState) {
            if ((this.FetchInvoicePdfOperationCompleted == null)) {
                this.FetchInvoicePdfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchInvoicePdfOperationCompleted);
            }
            this.InvokeAsync("FetchInvoicePdf", new object[] {
                        rfc,
                        key,
                        invoiceId,
                        ipAddress}, this.FetchInvoicePdfOperationCompleted, userState);
        }
        
        private void OnFetchInvoicePdfOperationCompleted(object arg) {
            if ((this.FetchInvoicePdfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchInvoicePdfCompleted(this, new FetchInvoicePdfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchInvoiceXml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FileContainerCarrier FetchInvoiceXml(string rfc, string key, int invoiceId, string ipAddress) {
            object[] results = this.Invoke("FetchInvoiceXml", new object[] {
                        rfc,
                        key,
                        invoiceId,
                        ipAddress});
            return ((FileContainerCarrier)(results[0]));
        }
        
        /// <remarks/>
        public void FetchInvoiceXmlAsync(string rfc, string key, int invoiceId, string ipAddress) {
            this.FetchInvoiceXmlAsync(rfc, key, invoiceId, ipAddress, null);
        }
        
        /// <remarks/>
        public void FetchInvoiceXmlAsync(string rfc, string key, int invoiceId, string ipAddress, object userState) {
            if ((this.FetchInvoiceXmlOperationCompleted == null)) {
                this.FetchInvoiceXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchInvoiceXmlOperationCompleted);
            }
            this.InvokeAsync("FetchInvoiceXml", new object[] {
                        rfc,
                        key,
                        invoiceId,
                        ipAddress}, this.FetchInvoiceXmlOperationCompleted, userState);
        }
        
        private void OnFetchInvoiceXmlOperationCompleted(object arg) {
            if ((this.FetchInvoiceXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchInvoiceXmlCompleted(this, new FetchInvoiceXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchPriceByGorilaId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool FetchPriceByGorilaId(int gorilaId, out decimal unitPrice, out string[] errors) {
            object[] results = this.Invoke("FetchPriceByGorilaId", new object[] {
                        gorilaId});
            unitPrice = ((decimal)(results[1]));
            errors = ((string[])(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void FetchPriceByGorilaIdAsync(int gorilaId) {
            this.FetchPriceByGorilaIdAsync(gorilaId, null);
        }
        
        /// <remarks/>
        public void FetchPriceByGorilaIdAsync(int gorilaId, object userState) {
            if ((this.FetchPriceByGorilaIdOperationCompleted == null)) {
                this.FetchPriceByGorilaIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchPriceByGorilaIdOperationCompleted);
            }
            this.InvokeAsync("FetchPriceByGorilaId", new object[] {
                        gorilaId}, this.FetchPriceByGorilaIdOperationCompleted, userState);
        }
        
        private void OnFetchPriceByGorilaIdOperationCompleted(object arg) {
            if ((this.FetchPriceByGorilaIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchPriceByGorilaIdCompleted(this, new FetchPriceByGorilaIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OfficesFranchisee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool OfficesFranchisee(string rfc, string key, [System.Xml.Serialization.XmlArrayAttribute("officesFranchisee")] out OfficeCarrier[] officesFranchisee1, out string[] errors) {
            object[] results = this.Invoke("OfficesFranchisee", new object[] {
                        rfc,
                        key});
            officesFranchisee1 = ((OfficeCarrier[])(results[1]));
            errors = ((string[])(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void OfficesFranchiseeAsync(string rfc, string key) {
            this.OfficesFranchiseeAsync(rfc, key, null);
        }
        
        /// <remarks/>
        public void OfficesFranchiseeAsync(string rfc, string key, object userState) {
            if ((this.OfficesFranchiseeOperationCompleted == null)) {
                this.OfficesFranchiseeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOfficesFranchiseeOperationCompleted);
            }
            this.InvokeAsync("OfficesFranchisee", new object[] {
                        rfc,
                        key}, this.OfficesFranchiseeOperationCompleted, userState);
        }
        
        private void OnOfficesFranchiseeOperationCompleted(object arg) {
            if ((this.OfficesFranchiseeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OfficesFranchiseeCompleted(this, new OfficesFranchiseeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BankAccountsFranchisee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool BankAccountsFranchisee(string rfc, string key, [System.Xml.Serialization.XmlArrayAttribute("bankAccountsFranchisee")] out BankAccountCarrier[] bankAccountsFranchisee1, out string[] errors) {
            object[] results = this.Invoke("BankAccountsFranchisee", new object[] {
                        rfc,
                        key});
            bankAccountsFranchisee1 = ((BankAccountCarrier[])(results[1]));
            errors = ((string[])(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void BankAccountsFranchiseeAsync(string rfc, string key) {
            this.BankAccountsFranchiseeAsync(rfc, key, null);
        }
        
        /// <remarks/>
        public void BankAccountsFranchiseeAsync(string rfc, string key, object userState) {
            if ((this.BankAccountsFranchiseeOperationCompleted == null)) {
                this.BankAccountsFranchiseeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBankAccountsFranchiseeOperationCompleted);
            }
            this.InvokeAsync("BankAccountsFranchisee", new object[] {
                        rfc,
                        key}, this.BankAccountsFranchiseeOperationCompleted, userState);
        }
        
        private void OnBankAccountsFranchiseeOperationCompleted(object arg) {
            if ((this.BankAccountsFranchiseeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BankAccountsFranchiseeCompleted(this, new BankAccountsFranchiseeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegisterPayment(string rfc, string key, int invoiceId, int bankAccount, out string[] errors) {
            object[] results = this.Invoke("RegisterPayment", new object[] {
                        rfc,
                        key,
                        invoiceId,
                        bankAccount});
            errors = ((string[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterPaymentAsync(string rfc, string key, int invoiceId, int bankAccount) {
            this.RegisterPaymentAsync(rfc, key, invoiceId, bankAccount, null);
        }
        
        /// <remarks/>
        public void RegisterPaymentAsync(string rfc, string key, int invoiceId, int bankAccount, object userState) {
            if ((this.RegisterPaymentOperationCompleted == null)) {
                this.RegisterPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterPaymentOperationCompleted);
            }
            this.InvokeAsync("RegisterPayment", new object[] {
                        rfc,
                        key,
                        invoiceId,
                        bankAccount}, this.RegisterPaymentOperationCompleted, userState);
        }
        
        private void OnRegisterPaymentOperationCompleted(object arg) {
            if ((this.RegisterPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterPaymentCompleted(this, new RegisterPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerCarrier {
        
        private System.Nullable<int> invoiceIdField;
        
        private string customerRFCField;
        
        private System.Nullable<System.DateTime> fechaDocumentoField;
        
        private decimal totalInvoiceField;
        
        private decimal totalImpuestosField;
        
        private string emailField;
        
        private string socialReasonField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string motherNameField;
        
        private string paymentMethodField;
        
        private string paymentConditionField;
        
        private string notesClientField;
        
        private string zipCodeField;
        
        private string streetField;
        
        private string poblacionField;
        
        private string municipioNameField;
        
        private int municipioIdField;
        
        private string estadoNameField;
        
        private int estadoIdField;
        
        private string exteriorNumberField;
        
        private string interiorNumberField;
        
        private string colonyField;
        
        private string versionField;
        
        private System.Nullable<int> officeIdField;
        
        private string monedaField;
        
        private decimal tipoCambioField;
        
        private string currencyNameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> InvoiceId {
            get {
                return this.invoiceIdField;
            }
            set {
                this.invoiceIdField = value;
            }
        }
        
        /// <comentarios/>
        public string CustomerRFC {
            get {
                return this.customerRFCField;
            }
            set {
                this.customerRFCField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaDocumento {
            get {
                return this.fechaDocumentoField;
            }
            set {
                this.fechaDocumentoField = value;
            }
        }
        
        /// <comentarios/>
        public decimal TotalInvoice {
            get {
                return this.totalInvoiceField;
            }
            set {
                this.totalInvoiceField = value;
            }
        }
        
        /// <comentarios/>
        public decimal TotalImpuestos {
            get {
                return this.totalImpuestosField;
            }
            set {
                this.totalImpuestosField = value;
            }
        }
        
        /// <comentarios/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <comentarios/>
        public string SocialReason {
            get {
                return this.socialReasonField;
            }
            set {
                this.socialReasonField = value;
            }
        }
        
        /// <comentarios/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <comentarios/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <comentarios/>
        public string MotherName {
            get {
                return this.motherNameField;
            }
            set {
                this.motherNameField = value;
            }
        }
        
        /// <comentarios/>
        public string PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
            }
        }
        
        /// <comentarios/>
        public string PaymentCondition {
            get {
                return this.paymentConditionField;
            }
            set {
                this.paymentConditionField = value;
            }
        }
        
        /// <comentarios/>
        public string NotesClient {
            get {
                return this.notesClientField;
            }
            set {
                this.notesClientField = value;
            }
        }
        
        /// <comentarios/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <comentarios/>
        public string Poblacion {
            get {
                return this.poblacionField;
            }
            set {
                this.poblacionField = value;
            }
        }
        
        /// <comentarios/>
        public string MunicipioName {
            get {
                return this.municipioNameField;
            }
            set {
                this.municipioNameField = value;
            }
        }
        
        /// <comentarios/>
        public int MunicipioId {
            get {
                return this.municipioIdField;
            }
            set {
                this.municipioIdField = value;
            }
        }
        
        /// <comentarios/>
        public string EstadoName {
            get {
                return this.estadoNameField;
            }
            set {
                this.estadoNameField = value;
            }
        }
        
        /// <comentarios/>
        public int EstadoId {
            get {
                return this.estadoIdField;
            }
            set {
                this.estadoIdField = value;
            }
        }
        
        /// <comentarios/>
        public string ExteriorNumber {
            get {
                return this.exteriorNumberField;
            }
            set {
                this.exteriorNumberField = value;
            }
        }
        
        /// <comentarios/>
        public string InteriorNumber {
            get {
                return this.interiorNumberField;
            }
            set {
                this.interiorNumberField = value;
            }
        }
        
        /// <comentarios/>
        public string Colony {
            get {
                return this.colonyField;
            }
            set {
                this.colonyField = value;
            }
        }
        
        /// <comentarios/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> OfficeId {
            get {
                return this.officeIdField;
            }
            set {
                this.officeIdField = value;
            }
        }
        
        /// <comentarios/>
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <comentarios/>
        public decimal TipoCambio {
            get {
                return this.tipoCambioField;
            }
            set {
                this.tipoCambioField = value;
            }
        }
        
        /// <comentarios/>
        public string CurrencyName {
            get {
                return this.currencyNameField;
            }
            set {
                this.currencyNameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BankAccountCarrier {
        
        private int idField;
        
        private string nameField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OfficeCarrier {
        
        private int idField;
        
        private string nameField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FileContainerCarrier {
        
        private string fileNameField;
        
        private string extensionField;
        
        private byte[] contentField;
        
        /// <comentarios/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <comentarios/>
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InvoiceCarrier {
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConceptCarrier {
        
        private int idField;
        
        private decimal quantityField;
        
        private decimal priceField;
        
        private string descriptionField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <comentarios/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <comentarios/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SignupCustomerCompletedEventHandler(object sender, SignupCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignupCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignupCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void InvoiceToCompletedEventHandler(object sender, InvoiceToCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InvoiceToCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InvoiceToCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string folioSerie {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FetchClientConceptsCompletedEventHandler(object sender, FetchClientConceptsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchClientConceptsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchClientConceptsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ConceptCarrier[] concepts {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConceptCarrier[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FetchClientInvoicesCompletedEventHandler(object sender, FetchClientInvoicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchClientInvoicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchClientInvoicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public InvoiceCarrier[] invoices {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvoiceCarrier[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FetchInvoicePdfCompletedEventHandler(object sender, FetchInvoicePdfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchInvoicePdfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchInvoicePdfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FileContainerCarrier Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FileContainerCarrier)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FetchInvoiceXmlCompletedEventHandler(object sender, FetchInvoiceXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchInvoiceXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchInvoiceXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FileContainerCarrier Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FileContainerCarrier)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FetchPriceByGorilaIdCompletedEventHandler(object sender, FetchPriceByGorilaIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchPriceByGorilaIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchPriceByGorilaIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public decimal unitPrice {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void OfficesFranchiseeCompletedEventHandler(object sender, OfficesFranchiseeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OfficesFranchiseeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OfficesFranchiseeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public OfficeCarrier[] officesFranchisee1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OfficeCarrier[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BankAccountsFranchiseeCompletedEventHandler(object sender, BankAccountsFranchiseeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BankAccountsFranchiseeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BankAccountsFranchiseeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public BankAccountCarrier[] bankAccountsFranchisee1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BankAccountCarrier[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void RegisterPaymentCompletedEventHandler(object sender, RegisterPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591