//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18033
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18033.
// 
#pragma warning disable 1591

namespace bsx.DirLaguna.Advertiser.ImageServicie {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ImageServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ImageService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveLogoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SavePictureOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveCouponSetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ImageService() {
            this.Url = global::bsx.DirLaguna.Advertiser.Properties.Settings.Default.bsx_DirLaguna_Advertiser_ImageServicie_ImageService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event SaveLogoCompletedEventHandler SaveLogoCompleted;
        
        /// <remarks/>
        public event SavePictureCompletedEventHandler SavePictureCompleted;
        
        /// <remarks/>
        public event SaveCouponSetCompletedEventHandler SaveCouponSetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveLogo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SaveLogo(int advertiserId, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] contentImg, string extension, out string[] errors) {
            object[] results = this.Invoke("SaveLogo", new object[] {
                        advertiserId,
                        contentImg,
                        extension});
            errors = ((string[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SaveLogoAsync(int advertiserId, byte[] contentImg, string extension) {
            this.SaveLogoAsync(advertiserId, contentImg, extension, null);
        }
        
        /// <remarks/>
        public void SaveLogoAsync(int advertiserId, byte[] contentImg, string extension, object userState) {
            if ((this.SaveLogoOperationCompleted == null)) {
                this.SaveLogoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveLogoOperationCompleted);
            }
            this.InvokeAsync("SaveLogo", new object[] {
                        advertiserId,
                        contentImg,
                        extension}, this.SaveLogoOperationCompleted, userState);
        }
        
        private void OnSaveLogoOperationCompleted(object arg) {
            if ((this.SaveLogoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveLogoCompleted(this, new SaveLogoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SavePicture", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SavePicture(int advertiserId, int galleryId, int newPictureId, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] contentImg, string extension, out string[] errors) {
            object[] results = this.Invoke("SavePicture", new object[] {
                        advertiserId,
                        galleryId,
                        newPictureId,
                        contentImg,
                        extension});
            errors = ((string[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SavePictureAsync(int advertiserId, int galleryId, int newPictureId, byte[] contentImg, string extension) {
            this.SavePictureAsync(advertiserId, galleryId, newPictureId, contentImg, extension, null);
        }
        
        /// <remarks/>
        public void SavePictureAsync(int advertiserId, int galleryId, int newPictureId, byte[] contentImg, string extension, object userState) {
            if ((this.SavePictureOperationCompleted == null)) {
                this.SavePictureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSavePictureOperationCompleted);
            }
            this.InvokeAsync("SavePicture", new object[] {
                        advertiserId,
                        galleryId,
                        newPictureId,
                        contentImg,
                        extension}, this.SavePictureOperationCompleted, userState);
        }
        
        private void OnSavePictureOperationCompleted(object arg) {
            if ((this.SavePictureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SavePictureCompleted(this, new SavePictureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveCouponSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SaveCouponSet(int advertiserId, int couponSetId, int newPictureId, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] contentImg, string extension, out string[] errors) {
            object[] results = this.Invoke("SaveCouponSet", new object[] {
                        advertiserId,
                        couponSetId,
                        newPictureId,
                        contentImg,
                        extension});
            errors = ((string[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SaveCouponSetAsync(int advertiserId, int couponSetId, int newPictureId, byte[] contentImg, string extension) {
            this.SaveCouponSetAsync(advertiserId, couponSetId, newPictureId, contentImg, extension, null);
        }
        
        /// <remarks/>
        public void SaveCouponSetAsync(int advertiserId, int couponSetId, int newPictureId, byte[] contentImg, string extension, object userState) {
            if ((this.SaveCouponSetOperationCompleted == null)) {
                this.SaveCouponSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveCouponSetOperationCompleted);
            }
            this.InvokeAsync("SaveCouponSet", new object[] {
                        advertiserId,
                        couponSetId,
                        newPictureId,
                        contentImg,
                        extension}, this.SaveCouponSetOperationCompleted, userState);
        }
        
        private void OnSaveCouponSetOperationCompleted(object arg) {
            if ((this.SaveCouponSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCouponSetCompleted(this, new SaveCouponSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SaveLogoCompletedEventHandler(object sender, SaveLogoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveLogoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveLogoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SavePictureCompletedEventHandler(object sender, SavePictureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SavePictureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SavePictureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SaveCouponSetCompletedEventHandler(object sender, SaveCouponSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCouponSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCouponSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591